# Environment: localhost
version: '3'

services:
  mud-database:
    container_name: mud-postgres
    image: postgres:13
    environment:
      POSTGRES_USER: 'demo_user'
      POSTGRES_PASSWORD: 'demo_pwd'
      POSTGRES_DB: 'demo_db'
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  mud-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mud-server
    volumes:
      - ./src:/src:rw
    ports:
      - '9878:9878'
    depends_on:
      - mud-database
    environment:
      DATABASEHOST: 'mud-database'
      DATABASENAME: 'demo_db'
      DATABASEUSER: 'demo_user'
      DATABASEPASSWORD: 'demo_pwd'
      DATABASEPORT: '5433'
