# Environment: localhost
version: '3'

services:
  mud-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mud-server
    volumes:
      - ./src:/src:rw
    ports:
      - '9878:9878'
