# Generated by Django 3.2.6 on 2021-08-08 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(help_text='Description of the room', verbose_name='Description')),
                ('name', models.CharField(help_text='Name of the room', max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the room', max_length=100, verbose_name='Name')),
                ('destination', models.ForeignKey(help_text='Room to exit to', on_delete=django.db.models.deletion.PROTECT, related_name='exit_destinations', to='world.room')),
                ('location', models.ForeignKey(help_text='Room to exit from', on_delete=django.db.models.deletion.PROTECT, related_name='exit_locations', to='world.room')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
